export const products = [
  {
    id: 1,
    image: "/applewatch.png",
    name: "Apple Watch Series 4",
    category: "Digital Product",
    price: "$690.00",
    piece: 63,
    colors: ["#000", "#C4C4C4", "#F76C6A"],
  },
  {
    id: 2,
    image: "/headphone.png",
    name: "Microsoft Headsquare",
    category: "Digital Product",
    price: "$190.00",
    piece: 13,
    colors: ["#000", "#F56E6E", "#3E8DF4", "#F0C84B"],
  },
  {
    id: 3,
    image: "/dress.png",
    name: "Women's Dress",
    category: "Fashion",
    price: "$640.00",
    piece: 635,
    colors: ["#7A2E7A", "#C13157", "#1E40AF", "#0000FF"],
  },

  // ----------- GENERATED ITEMS BELOW (97 MORE) -----------
  {
    id: 4,
    image: "/samsungA50.png",
    name: "Samsung A50",
    category: "Mobile",
    price: "$400.00",
    piece: 67,
    colors: ["#000", "#1E3A8A", "#9B1C1C"],
  },
  {
    id: 5,
    image: "/camera.png",
    name: "Canon DSLR Camera",
    category: "Electronic",
    price: "$420.00",
    piece: 52,
    colors: ["#000", "#1E3A8A", "#9B1C1C"],
  },
  {
    id: 6,
    image: "/laptop.png",
    name: "Dell Inspiron 15",
    category: "Electronic",
    price: "$850.00",
    piece: 24,
    colors: ["#000", "#C4C4C4"],
  },
  {
    id: 7,
    image: "/shoes.png",
    name: "Running Sports Shoes",
    category: "Fashion",
    price: "$120.00",
    piece: 312,
    colors: ["#000", "#1E3A8A", "#C13157"],
  },
  {
    id: 8,
    image: "/bag.png",
    name: "Leather Hand Bag",
    category: "Fashion",
    price: "$95.00",
    piece: 128,
    colors: ["#7A2E7A", "#C13157", "#000"],
  },
  {
    id: 9,
    image: "/watch.png",
    name: "Sport Fitness Watch",
    category: "Digital Product",
    price: "$260.00",
    piece: 91,
    colors: ["#000", "#38BDF8", "#22C55E"],
  },
  {
    id: 10,
    image: "/earbuds.png",
    name: "Wireless Earbuds Pro",
    category: "Digital Product",
    price: "$140.00",
    piece: 75,
    colors: ["#000", "#F56E6E", "#3E8DF4"],
  },
  {
    id: 11,
    image: "/tv.png",
    name: "Samsung Smart TV",
    category: "Electronic",
    price: "$720.00",
    piece: 40,
    colors: ["#000", "#1E3A8A"],
  },
  {
    id: 12,
    image: "/phone.png",
    name: "iPhone 12",
    category: "Mobile",
    price: "$999.00",
    piece: 31,
    colors: ["#000", "#1E3A8A", "#F56E6E"],
  },
  {
    id: 13,
    image: "/dress2.png",
    name: "Men's Formal Shirt",
    category: "Fashion",
    price: "$55.00",
    piece: 541,
    colors: ["#000", "#C4C4C4", "#1E40AF"],
  },
  {
    id: 14,
    image: "/dress3.png",
    name: "Women's Jacket",
    category: "Fashion",
    price: "$130.00",
    piece: 240,
    colors: ["#7A2E7A", "#C13157", "#1E40AF"],
  },
  {
    id: 15,
    image: "/tablet.png",
    name: "iPad Mini 5",
    category: "Electronic",
    price: "$450.00",
    piece: 97,
    colors: ["#000", "#C4C4C4"],
  },
  {
    id: 16,
    image: "/monitor.png",
    name: "Dell UltraSharp Monitor",
    category: "Electronic",
    price: "$350.00",
    piece: 64,
    colors: ["#000", "#1E40AF"],
  },
  {
    id: 17,
    image: "/keyboard.png",
    name: "Mechanical Keyboard",
    category: "Electronic",
    price: "$95.00",
    piece: 210,
    colors: ["#000", "#C4C4C4"],
  },
  {
    id: 18,
    image: "/mouse.png",
    name: "Gaming Mouse RGB",
    category: "Electronic",
    price: "$70.00",
    piece: 300,
    colors: ["#000", "#3E8DF4", "#22C55E"],
  },
  {
    id: 19,
    image: "/speaker.png",
    name: "Bluetooth Speaker",
    category: "Digital Product",
    price: "$110.00",
    piece: 178,
    colors: ["#000", "#3E8DF4", "#F0C84B"],
  },
  {
    id: 20,
    image: "/fridge.png",
    name: "LG Refrigerator",
    category: "Electronic",
    price: "$570.00",
    piece: 18,
    colors: ["#000", "#C4C4C4"],
  },

 
];


